networks:
  manual_network:
    name: manual_network

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: GKCJA5P@
      MYSQL_DATABASE: digitalizacionmod2
      MYSQL_USER: manual
      MYSQL_PASSWORD: GKCJA5P@
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - manual_network
